FROM registry.redhat.io/rhel8/go-toolset:1.17.7-13 AS builder
WORKDIR /go/src/github.com/openshift/shared-resources-operator
COPY . .
COPY vendor/github.com/openshift/api/sharedresource/v1alpha1/*.crd.yaml assets/
RUN make update
RUN make

FROM quay.io/openshift/origin-cli:4.11
COPY --from=builder /go/src/github.com/openshift/shared-resources-operator/shared-resources-operator /usr/bin/
ENTRYPOINT ["/usr/bin/shared-resources-operator"]
