# Allow AWS EBS CSI driver operator to read CA bundle from openshift-config-managed/kube-cloud-config ConfigMap
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shared-resource-csi-driver-operator-aws-config-role
  namespace: openshift-config-managed
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
